version: 2

sources:
  - name: raw
    database: OLIST_DB
    schema: RAW

    tables:
      - name: customers
        identifier: CUSTOMERS

      - name: orders
        identifier: ORDERS

      - name: order_items
        identifier: ORDER_ITEMS

      - name: order_payments
        identifier: ORDER_PAYMENTS

      - name: order_reviews
        identifier: ORDER_REVIEWS

      - name: products
        identifier: PRODUCTS

      - name: sellers
        identifier: SELLERS

      - name: geolocation
        identifier: GEOLOCATION

      - name: product_category_translation
        identifier: PRODUCT_CATEGORY_TRANSLATION